mysite/food/urls.py
from django.urls import path,include
from food import views
 
app_name = 'food'

urlpatterns = [
    # function based index view
    # -------------------------------------------------------------------------------
    path('home/', views.index, name='index'),

    # class based index view
    # -------------------------------------------------------------------------------
    #path('home/', views.IndexClassView.as_view(), name='index'),

    # function based detail view
    # -------------------------------------------------------------------------------
    path('detail/<int:item_id>/', views.detail, name='detail'),

    # class based detail view
    # -------------------------------------------------------------------------------
    #path('detail/<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    # function based create item view
    # -------------------------------------------------------------------------------
    # path('add/',views.create_item,name='create_item'),
    #class based create item view
    #--------------------------------------------------------------------------------
    path('add/',views.CreateItem.as_view(),name='create_item'),
    # function based update item view
    # -------------------------------------------------------------------------------
    path('update/<int:id>/', views.update_item, name='update_item'),
    # function based delete item view
    # -------------------------------------------------------------------------------
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('users/', include('users.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', users_views.login_view, name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
]
urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from users import views
from django.urls import path

app_name = 'users'
urlpatterns = [

    # orders
    path('orders/<int:id>/<int:pdcd>/<str:user>/', views.Orders, name='orders'),
        
    #updating customer orders   
    path('upd_orders/,<int:upd_orders_id>/',views.update_orders,name='upd_orders'),
 
    # customer rating-feedback view

    path('crf/<int:it_id>/<int:pc>/', views.CusRatFeed, name='CusRatFeed'),
    
    #updating customer ratings and feedbacks
    path('crf/<int:details_id>/<int:crf_id>/',views.update_crf,name='upd_crf')


    ]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
# Create   your models here.

class Item(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default='1'
    )
    prod_code=models.IntegerField(default=100)
    for_user=models.CharField(max_length=100,default="xyz")    
    item_name=models.CharField(max_length=50)
    item_desc=models.CharField(
        max_length=500,
        default='''Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis quae nemo ducimus, aperiam reprehenderit sit provident quam, enim tempore ea eligendi vel facere? In numquam deleniti, debitis quod odit tenetur.'''
        )
    item_price=models.IntegerField()
    item_image=models.CharField(
        max_length=500,
        default="https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png"
    )
    def __str__(self):
        return self.item_name
class History(models.Model):

    user_name=models.CharField(max_length=100)
    prod_ref=models.IntegerField(default=100)
    item_name=models.CharField(max_length=200)
    op_type=models.CharField(max_length=100)

    def __str__(self):
        return str(
            (
                self.prod_ref,
                self.user_name,
                self.item_name,
                self.op_type
            )
        )

mysite/food/forms.py
from django import forms
from food.models import Item 

class Itemform(forms.ModelForm):
    class Meta:
        model=Item
        fields=['prod_code','for_user','item_name','item_desc','item_price','item_image']

        

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from food.models import Item
from food.forms import Itemform
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from food.models import History
from users.models import CusOrders,CusRatingFeedback
# Create your views here.
# -------------------------------------------------------------------------------


# function based index view
# -------------------------------------------------------------------------------

def index(request):
    
    if request.user.is_superuser:
        itemlist = Item.objects.all()

    elif request.user.is_authenticated and request.user.profile.user_type == 'Rest':
        itemlist = Item.objects.filter(for_user = request.user.username)

    elif request.user.is_authenticated and request.user.profile.user_type == 'Cust':
        itemlist = Item.objects.all()

    else:
        itemlist = Item.objects.all()

    itemlist= Item.objects.all()
    context={
        'itemlist':itemlist
    }
    return render(request, 'food/index.html',context)
# class based index view
# ------------------------- ------------------------------------------------------

class IndexClassView(ListView):

    model = Item
    context_object_name = 'itemlist'
    template_name = 'food/index.html'


# function based detail v iew
# ---------------------------   ------ --   --------------------------------------------
def detail(request,item_id):

    item=Item.objects.get(pk=item_id )
    
    hist=History.objects.filter(
        prod_ref=item.prod_code)
    
    Obj_CusOrd = CusOrders.objects.filter(
        prod_code=item.prod_code
    )
     # restaurant and admin
    if request.user.profile.user_type == 'Rest' or request.user.profile.user_type == 'Admin':
        Obj_CusOrd = CusOrders.objects.filter(
            prod_code = item.prod_code
        )

    # customer
    elif request.user.profile.user_type == 'Cust':
        Obj_CusOrd = CusOrders.objects.filter(
            prod_code = item.prod_code,
            user = request.user.username
        )
    crf=CusRatingFeedback,object.filter(
        prod_code=item.prod_code

    )
    context={
        'item':item,
        'hist':hist,
        'oco':Obj_CusOrd,
        'crf':crf
        
    }
    return render(request,'food/detail.html',context)

    # class based detail view
# -------------------------------------------------------------------------------

class FoodDetail(DetailView):

    model = Item
    context_object_name = 'item'
    template_name = 'food/detail.html'
# function based create item view
# -------------------------------------------------------------------------------
def create_item(request):

    form= Itemform(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    context={
        'form':form
    }
    return render(request,'food/item-form.html',context)
# function based update item view
# -------------------------------------------------------------------------------

def update_item(request, id):

    item = Item.objects.get(pk=id)
    form = Itemform(request.POST or None, instance=item)

    context = {
    'form':form
    }

    if form.is_valid():
        form.save()
        obj_History=History(
            user_name=request.user.username,
            prod_ref=form.instance.prod_code,
            item_name=request.POST.get('item_name'),       #form.instance.item_name
            op_type='updated'

        )
        obj_History.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', context)
#class based create item view
#--------------------------------------------------------------------------
class CreateItem(CreateView):
    model=Item
    fields=['prod_code','for_user','item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'
    success_url=reverse_lazy('food:index')

    def form_valid(self,form):
        form.instance.user=self.request.user

        obj_History=History(
            user_name=self.request.user.username,
            prod_ref=form.instance.prod_code,
            item_name=self.request.POST.get('item_name'),       #form.instance.item_name
            op_type='created'

        )
        obj_History.save()

        return super().form_valid(form)
    

# function based delete item view
# -------------------------------------------------------------------------------
def delete_item(request, id):

    item = Item.objects.get(pk=id)

    context = {
    'item':item
    }

    if request.method == 'POST':
        Obj_History = History(
            user_name = request.user.username,
            prod_ref = item.prod_code,
            item_name = item.item_name,
            op_type = 'Deleted'
        )

        Obj_History.save()
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html', context)

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM " crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="{ % url 'food:index' %}" class="navbar-brand">
            Exortillo
        </a>
        <div class="navbar">
        {% if user.is_superuser %}

            <a href="{% url 'food:create_item' %}" class="nav-item nav-link btn btn-dark">
                Add Item
            </a>

            <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-dark">
                Profile
            </a>

            <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-dark">
                Logout
            </a>
            
        {% elif user.is_authenticated %}

            <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-dark">
                Profile
            </a>

            <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-dark">
                Logout
            </a>

        {% else %}

            <a href="{% url 'login' %}" class="nav-item nav-link btn btn-dark">
                Login
            </a>

            <a href="{% url 'register' %}" class="nav-item nav-link btn btn-dark">
                Sign Up
            </a>

        {% endif %}

        </div>
    </nav>
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}

    {% endif %}
    <!-- for spacing -->
    <div class="mb-5"></div>
    {% block body %}
    {% endblock %}
    
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <div class="row">
            <div class="col-md-2 offset-md-1">
                <img height="150px"
                     width="250px"
                     class="card"
                     src="{{ item.item_image }}">
            </div>

            <div class="col-md-4 offset-md-1">
                <h1 
                    style="
                        font-style: italic;">
                    {{ item.item_name }}
                </h1>

                <h2
                style="
                        font-style: italic;
                        font-size: 1.3rem;
                        text-align: justify;">
                    {{ item.item_desc }}
                </h2>

                <h3>
                    ${{ item.item_price}}
                </h3>
            </div>

            <div class="col-md-3 offset-md-1">
                {% if user.is_superuser %}
                    <a
                        href="{% url 'food:update_item' item.id %}"
                        style="width: 80px;"
                        class="btn btn-warning"
                    >
                    Edit
                    </a>
                    
                    <a
                        href="{% url 'food:update_item' item.id %}"
                        style="width: 80px;"
                        class="btn btn-warning"
                    >
                    Delete
                    </a> 
                    
                    <a
                    href="{% url 'food:index' %}"
                    style="width: 80px"
                    class="btn btn-success">
                    Back
                    </a>  

                {% elif user.is_authenticated and user.profile.user_type == 'Rest' %}
                    <a
                        href="{% url 'food:update_item' item.id %}"
                        style="width: 80px;"
                        class="btn btn-warning"
                    >
                    Edit
                    </a> 
                        
                    <a
                    href="{% url 'food:index' %}"
                    style="width: 80px"
                    class="btn btn-success">
                    Back
                    </a>
                {% elif user.is_authenticated and user.profile.user_type == 'Cust' %}
                    <a
                        href="{% url 'users:orders' item.id item.prod_code user.username %}"
                        style="width: 80px;"
                        class="btn btn-warning"
                    >
                    Order
                    </a> 
                        
                    <a
                    href="{% url 'food:index' %}"
                    style="width: 80px"
                    class="btn btn-success"
                    >
                    Back
                    </a>
                {% endif %} 
            </div>  
        </div> 
{%if user.is_authenticated %} 
<!--red-->
    {% if user.profile.user_type == 'Rest' or user.profile.user_type == 'admin'  %}


        {% for obj in hist %}

        <div
            class="row mb-1">

            <div
                class="col-md-8
                    offset-md-2
                    bg-danger
                    text-white">

                    <div
                        class="row">

                        <div 
                            class="col-md-3 
                                text-left">
                            {{ obj.user_name }}
                        </div>
                        <div 
                            class="col-md-3 
                                text-left">
                            {{ obj.prod_ref }}
                        </div>
                        <div 
                            class="col-md-3 
                                text-left">
                            {{ obj.item_name }}
                        </div>
                        <div 
                            class="col-md-3 
                                text-left">
                            {{ obj.op_type }}
                        </div>

                    </div>

            </div>
            <div
                class="col-md-2">


            </div>
            
        </div>

        {% endfor %}

    {% endif %}

    <!-- green -->

    {% if user.profile.user_type == 'Rest' or user.profile.user_type == 'Cust' or user.profile.user_type == 'Admin' %}

        {% for obj in oco %}

            <div
                class="row mb-1">

                <div
                    class="col-md-8
                        offset-md-2
                        bg-success
                        text-white">

                        <div
                            class="row">

                            <div 
                                class="col-md-2
                                    text-left">

                                {{ obj.order_id }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.prod_code }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.quantity }}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {{ obj.user }}
                            </div>
                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if user.profile.user_type == 'Cust' %}
                                    <a
                                        class="btn btn-warning btn-sm"
                                        href="{% url 'users:upd_orders' item.id obj.order_id %}">

                                        Edit Qty
                                    </a>
                                {% endif %}
                            </div>

                            <div 
                                class="col-md-2 
                                    text-left">

                                {% if user.profile.user_type == 'Cust' %}
                                    <a
                                        class="btn btn-primary btn-sm"
                                        href="#">

                                        Buy Now
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                </div>

                <div
                    class="col-md-2">

                </div>

            </div>

        {% endfor %}

    {% endif %}
     <!-- add feedback and ratings button -->

     {% if user.profile.user_type == 'Cust' %}
    <a class="btn btn-dark offset-md-5 mb-2" href="{% url 'users:CusRatFeed' item.id item.prod_code %}">
         Add Ratings and Feedback
    </a>
 {% endif %}

 <!-- blue -->

 {% if user.profile.user_type == 'Rest' or user.profile.user_type == 'Cust' or user.profile.user_type == 'Admin' %}

     {% for obj in crf %}

         <div
             class="row mb-1">

             <div
                 class="col-md-8
                     offset-md-2
                     bg-info
                     text-white">

                     <div
                         class="row">

                         <div 
                             class="col-md-1 
                                 text-left">

                             {{ obj.prod_code }}
                         </div>

                         <div 
                             class="col-md-1 
                                 text-left">

                             {{ obj.ratings }}
                         </div>

                         <div 
                             class="col-md-2 
                                 text-left">

                             {{ obj.feedback }}
                         </div>

                         <div 
                             class="col-md-2 
                                 text-left">

                             {{ obj.username }}
                         </div>

                         <div 
                             class="col-md-2 
                                 text-left">

                             {{ obj.user_type }}
                         </div>

                         <div 
                             class="col-md-2 
                                 text-left">

                             {% if obj.username == user.username %}
                                 <a
                                     class="btn btn-warning btn-sm"
                                     href="{% url 'users:upd_crf' item.id %}">

                                     Edit
                                 </a>
                             {% endif %}
                         </div>

                         <div 
                             class="col-md-2 
                                 text-left">

                             {% if obj.username == user.username %}
                                 <a
                                     class="btn btn-primary btn-sm"
                                     href="#">

                                     Delete
                                 </a>
                             {% endif %}
                         </div>
                     </div>
             </div>

             <div
                 class="col-md-2">

             </div>

         </div>

     {% endfor %}

 {% endif %}

{% endif %}

{% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    
    {% for item in itemlist %}
        <div class="row mb-3">
           <div class="col-md-3 offset-md-2 ">
            <img src="{{ item.item_image }}"
             class="card"
             height="135px"
             width="230px">

            </div>
            <div class="col-md-4">
                <h3
                style="font-size: 1.5rem;"
                >
                    {{item.item_name}}
                </h3>
                <h5
                    style="font-style: italic;
                    font-size: 1rem;"
                >
                    {{item.item_desc | truncatewords:6}}
                </h5>
                <h6>
                    ${{item.item_price}}
                </h6>
                
                <h6
                    style="font-style: italic;" >
                 Added for:{{ item.for_user }}               
                </h6>
                <h6
                    style="font-style: italic;" >
                    Added by superuser:{{ item.user }}
          
                </h6>
            </div>
            <div class="col-md-3">
                {% if user.is_authenticated %}
                <a 
                    href="{% url 'food:detail' item.id %}"
                    style="width:100px"
                    class="btn btn-success">
                    details 
                </a>
                {% endif %}
            </div>

        </div>
        
    {% endfor %}

    {% endblock %}
</body>
</html>

mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete, {{ item.item_name }}</h3>
    <button type="submit">Confirm</button>
</form>

{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<br><br><br>
<div class="container" >
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Sign Up

                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <label class="offset-md-1">Product Code: </label><br>
                        <span class="offset-md-1">{{ form.prod_code }}</span><br>

                        <label class="offset-md-1">For User: </label><br>
                        <span class="offset-md-1">{{ form.for_user }}</span>

                        <label class="offset-md-1">Item Name: </label><br>
                        <span class="offset-md-1">{{ form.item_name }}</span>

                        <label class="offset-md-1">Item Description: </label><br>
                        <span class="offset-md-1">{{ form.item_desc }}</span> 

                        <label class="offset-md-1">Item Price: </label><br>
                        <span class="offset-md-1">{{ form.item_price }}<span>

                        <label class="offset-md-1">Item Image: </label><br>
                        <span class="offset-md-1">{{ form.item_image }}</span><br>

                        <br><button class="btn btn-success btn-sm offset-md-4" type="submit">Save</button>
                    </form>
                </div>
            </div>


        </div>
    </div>

</div>
<br><br><br>


{% endblock %}